server:
  port: 8080

spring:

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: orchestrator-group # consumer group id, cada app vai ter o seu consumer group!
      auto-offset-reset: latest

logging:
  level:
    org:
      apache:
        kafka: OFF