server:
  port: 8092

spring:

    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST:localhost}:5432/inventory-db
      username: usuario
      password: senha

    jpa:
      hibernate:
        ddl-auto: create-drop # quando eu paro e starto a aplicação ele da um drop e cria o banco do zero! bom para test
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true
          use_sql_comments: true